export const tagTypes = {
  USER_INFO: "user_info",
  USERS: "users",
  STARTUP_IDEAS: "startup_ideas",
  SERVICE_MANAGEMENT: "service_management",
  PROPOSALS: "proposals",
  CONVERSATION: "conversations",
  MESSAGES: "messages",
  AGREEMENTS: "agreements",
  INVOICE: "invoice",
  DISPUTES: "disputes",
  SITE_SETTINGS_CONTENT: "site_settings_content",
  CMS_CONTENT: "cms_content",
  STRIPE: "stripe",
  PAYMENT: "payment",
  RE_PAYMENT: "re_payment",
  BANK_DETAILS: "bank_details",
  SETTINGS: "settings",
  NOTIFICATION: "notification",
  NEW_ADMIN: "new_admin",
  ROLE_PERMISSIONS: "role_permissions",
  BLOGS: "blogs",
  DD_STARTUP_CATEGORIES: "dd_startup_categories",
  DD_CURRENCIES: "dd_currencies",
  DD_FUNDING_STAGES: "dd_funding_stages",
  REVIEW: "review",
  USER_REVIEW: "user_review",
  CONTACT_US: "contact_us",
};

export const tagTypesList = Object.values(tagTypes);
